name: chess
channels:
  - conda-forge
dependencies:
  - dash=2.13
  - lxml==4.9.3
  - python=3.11
  - pip:
      - dash-svg==0.0.12
      - dash-extensions
      - stockfish==3.28.0
      - python-dotenv==1.0.0
